### ISSUE TITLE
Add to Starlette "Third party middleware" docs?

### ISSUE THREAD

**Issue by tomchristie** [simonw/datasette-auth-github#33]
You might want to consider adding this and `datasette-cors` to Starlette's third-party-middleware docs. https://www.starlette.io/middleware/#third-party-middleware

At some point we could really do with a more general place for promoting cross-ASGI middleware & components, but that's probably a decent place in the meantime.

**Comment by simonw** [comment]
Weirdly enough, I just spotted that section of your docs ten minutes ago and was starting to mentally construct a pull request.

datasette-cors is pretty similar to Starlette's own version, but happy to include that too.

**Comment by simonw** [comment]
I'm also planning a datasette-gzip plugin which is the thinnest possible wrapper around the Starlette one (just the code that turns it into a plugin).
