### ISSUE TITLE
Allowing alternative oauth providers

### ISSUE THREAD

**Issue by ananis25** [simonw/datasette-auth-github#56]
Hi @simonw - I read in the datasette updates recently that you plan to implement Google oauth (or use the Django plugins). 

I posted a [PR](#52) some months back that does a refactoring to the GitHubAuth class so it could be inherited and adapted for different OAuth providers like Google (explained here - #3). Wondering If you missed it, could you please take a look and see if it seems useful?

**Comment by simonw** [comment]
I've upgraded authentication to be a core concept within Datasette in the forthcoming Datasette 0.44 (hopefully out within a day or two): https://datasette.readthedocs.io/en/latest/authentication.html

This should make it much easier to build similar plugins to this one that handle other providers.
